default: &default
  title: VVeib0

  mailer:
    smtp_settings:
      # address:
      # port:
      # domain:
      # user_name:
      # password:
      # authentication:
      enable_starttls_auto: true

    default_url_options:
      host: localhost:3000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
