default: &default
  title: VVeib0

  mailer:
    smtp_settings:
      address: 'smtp.gmail.com'
      port: 587
      enable_starttls_auto: true
      # domain:
      # user_name:
      # password:
      # authentication:

    default_options:
      from: no-reply@example.com
    default_url_options:
      host: localhost:3000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
