default: &default
  title: VVeib0

  mailer:
    smtp_settings:
      address: 'smtp.gmail.com'
      port: 587
      enable_starttls_auto: true
      domain: 'gmail.com'
      # user_name:
      # password:
      authentication: 'plain'

    default_url_options:
      # host: localhost:3000

  omniauth:
    # github_id:
    # github_secret:

development:
  <<: *default
  admin_emails:
    # - admin@example.com

test:
  <<: *default

production:
  <<: *default
